name: build-binary

on:
  push:
    branches: '*'
  pull_request:
    types: 
      - opened

jobs:
  build-binary:
    name: build-binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: build
        run: cargo build