name: static-code-check

on:
  push:
    branches: '*'
  pull_request:
    types: 
      - opened

env:
  CARGO_TERM_COLOR: always

jobs:
  format-check:
    name: format-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Format check
        run: make fmt-check

  # clippy-check:
  #   name: clippy-check
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v4

  #     - name: Clippy check
  #       run: make clippy-check